{
  "parserOptions": {
    "ecmaVersion": 2017
  },
  "env": {
    "mocha": true,
    "node": true
  },
  extends: "airbnb-base",
  rules: {
    no-console: 0,
    no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  }
}
